### PR TITLE
Development

### PR DESCRIPTION
**Pull request by fwxs**
First version of "Tweet Cleaner" script.
Best if used while iterating what's returned from the map function (According to the ipython %timeit magic function).

### CODE REVIEW

**Comment by eecopa** [comment]
Are we removing the emojis? I didn't see that step in the code. Apart from that, the overall code looks good to me. Good work! @fwxs

**Comment by fwxs** [comment]
Good point, emojis could be useful on the training/test process.

**Comment by fwxs** [comment]
I updated the cleaner script, now it'll replace punctuation characters and stopwords.

**Comment by eecopa** [comment]
This was closed. Decided to reopen it due to an error from fwxs while making a PR again.

**Pull request merged**
